name: Strapi Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout le code de ton repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Connexion à DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extraire la version à partir du tag
      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Construction de l'image Docker avec le tag versionné
      - name: Build Docker image
        working-directory: ./back # On se place dans le dossier "back"
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dreamsite-admin:${{ env.VERSION }} .

      # Pousser l'image versionnée vers DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dreamsite-admin:${{ env.VERSION }}
