name: Image Docker Dev

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet le déclenchement manuel depuis l'interface GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Construction de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t dreamsite-admin:${{ github.ref_name }} .

      # Étape 4 : (Optionnel) Push de l'image vers un registre Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag dreamsite-admin:develop kevinad/dreamsite-admin
          docker push kevinad/dreamsite-admin:develop
